---
version: "3.8"

networks:
  proxy-tier:

services:
  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run.docker.sock
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-ngin-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  vhost.d:
  certs:
  html:
