---
version: "3.8"

services:
  db:
    build:
      context: ./db
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - db:/var/lib/postgresql/data
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - nextcloud

  cache:
    build:
      context: ./cache
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    restart: always
    networks:
      - nextcloud

  smtp:
    build:
      context: ./smtp
    restart: always
    networks:
      - nextcloud

  cron:
    build:
      context: ./nextcloud
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud/config/cronfile:/var/spool/cron/crontabs/www-data
    entrypoint: /cron.sh
    depends_on:
      - db
      - cache
    networks:
      - nextcloud

  nextcloud:
    build:
      context: ./nextcloud
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION}
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_TRUSTED_DOMAINS: $NEXTCLOUD_TRUSTED_DOMAINS
      REDIS_HOST: cache
      SMTP_HOST: smtp
    links:
      - db
      - cache
      - smtp
    depends_on:
      - db
      - cache
      - smtp
    volumes:
      - nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - nextcloud

  web:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    links:
      - nextcloud
    depends_on:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nextcloud

networks:
  nextcloud:

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt

volumes:
  nextcloud:
  db:
